local g = require 'helpers.globals'
local k = require 'helpers.keymaps'

k.set_('<space>', '<nop>')
g.leader ' '

g.unset 'tar'
g.unset 'zip'
g.unset 'gzip'
g.unset 'netrw'
g.unset 'logipat'
g.unset 'matchit'
g.unset 'vimball'
g.unset 'rrhelper'
g.unset 'getscript'
g.unset 'tarPlugin'
g.unset 'zipPlugin'
g.unset 'matchparen'
g.unset 'netrwPlugin'
g.unset '2html_plugin'
g.unset 'netrwSettings'
g.unset 'vimballPlugin'
g.unset 'getscriptPlugin'
g.unset 'spellfile_plugin'
g.unset 'netrwFileHandlers'
